CREATE TABLE IF NOT EXISTS CLASSE
(
    ID     SERIAL PRIMARY KEY,
    NOM    VARCHAR(255) NOT NULL,
    NIVEAU VARCHAR(255) NOT NULL,
    CONSTRAINT UK_NIVEAU UNIQUE (NIVEAU)
);
CREATE UNIQUE INDEX ON CLASSE (NIVEAU);

CREATE TABLE IF NOT EXISTS ELEVE
(
    ID             SERIAL PRIMARY KEY,
    NOM            VARCHAR(255) NOT NULL,
    PRENOM         VARCHAR(255) NOT NULL,
    DATE_NAISSANCE TIMESTAMP NOT NULL,
    ID_CLASSE      INT       NOT NULL,
    CONSTRAINT FK_CLASSE FOREIGN KEY (ID_CLASSE) REFERENCES CLASSE (ID)
);
CREATE INDEX ON ELEVE (ID_CLASSE);