INSERT INTO CLASSE (NOM, NIVEAU) VALUES ('CP 1', 'CP');

INSERT INTO ELEVE (NOM, PRENOM, DATE_NAISSANCE, ID_CLASSE) VALUES ('Doe', 'John', NOW(), (SELECT ID FROM CLASSE WHERE NIVEAU = 'CP'));
INSERT INTO ELEVE (NOM, PRENOM, DATE_NAISSANCE, ID_CLASSE) VALUES ('Doe', 'Jane', NOW(), (SELECT ID FROM CLASSE WHERE NIVEAU = 'CP'));